from typing import List, Set, Tuple
from backend.models import ReceiptData, DescriptionData


def cross_check_extraction_and_parsing(
    receipt: ReceiptData,
    description: DescriptionData
) -> List[str]:
    """Cross-checks structured extraction and description parsing outputs.
    
    Verifies:
    1. Every item name in description.item_assignments actually exists in receipt.items.
    2. Every receipt line item is either assigned in item_assignments or accounted for
       in unclear_references / unmatched_mentions — no receipt item vanishes without a trace.
       
    Returns:
        List[str]: Quality audit flags generated by the cross-check.
    """
    flags: List[str] = []

    # Map receipt items (normalized -> original name)
    receipt_items_map = {item.name.strip().lower(): item.name for item in receipt.items}

    # 1. Verify every assigned item in description exists on the receipt
    for assignment in description.item_assignments:
        assign_norm = assignment.item_name.strip().lower()
        matched = False
        for r_norm, r_orig in receipt_items_map.items():
            if assign_norm == r_norm or assign_norm in r_norm or r_norm in assign_norm:
                matched = True
                break
        if not matched:
            flag_msg = f"Assigned item '{assignment.item_name}' does not match any item on the receipt."
            flags.append(flag_msg)
            if assignment.item_name not in description.unmatched_mentions:
                description.unmatched_mentions.append(assignment.item_name)

    # 2. Verify every receipt item was assigned or explicitly accounted for
    assigned_receipt_names: Set[str] = set()
    for item in receipt.items:
        item_norm = item.name.strip().lower()
        for assignment in description.item_assignments:
            assign_norm = assignment.item_name.strip().lower()
            if (item_norm == assign_norm or item_norm in assign_norm or assign_norm in item_norm) and assignment.consumed_by:
                assigned_receipt_names.add(item.name)
                break

    for item in receipt.items:
        if item.name not in assigned_receipt_names:
            # Check if mentioned in unclear_references
            item_norm = item.name.strip().lower()
            in_unclear = any(item_norm in ur.strip().lower() for ur in description.unclear_references)
            if not in_unclear:
                flags.append(
                    f"Receipt item '{item.name}' was not explicitly assigned in description; defaulted to shared across group."
                )

    return flags
